//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDITORIA
    {
        public decimal ID_AUDITORIA { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public string NOMBRE_FUNCIONARIO { get; set; }
        public string IP { get; set; }
        public string HOST { get; set; }
        public string ROL { get; set; }
        public string ACCION { get; set; }
    }
}
