//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASE_DATOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BASE_DATOS()
        {
            this.SERVICIOS = new HashSet<SERVICIOS>();
            this.SISTEMA = new HashSet<SISTEMA>();
        }
    
        public string COD_BASE_DATOS { get; set; }
        public string NOM_USUARIO { get; set; }
        public decimal ID_MOTOR { get; set; }
        public string COD_SERVIDOR { get; set; }
    
        public virtual MODULO MODULO { get; set; }
        public virtual MOTOR_BASE_DATOS MOTOR_BASE_DATOS { get; set; }
        public virtual SERVIDOR SERVIDOR { get; set; }
        public virtual HASH_PASS_BASE_DATOS HASH_PASS_BASE_DATOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIOS> SERVICIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SISTEMA> SISTEMA { get; set; }
    }
}
