//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HomeroSystemEntities : DbContext
    {
        public HomeroSystemEntities()
            : base("name=HomeroSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BASE_DATOS> BASE_DATOS { get; set; }
        public virtual DbSet<DOCUMENTO> DOCUMENTO { get; set; }
        public virtual DbSet<EQUIPO_TRABAJO> EQUIPO_TRABAJO { get; set; }
        public virtual DbSet<FUNCIONARIO> FUNCIONARIO { get; set; }
        public virtual DbSet<HASH_PASS> HASH_PASS { get; set; }
        public virtual DbSet<HASH_PASS_BASE_DATOS> HASH_PASS_BASE_DATOS { get; set; }
        public virtual DbSet<HASH_PASS_SERVIDOR> HASH_PASS_SERVIDOR { get; set; }
        public virtual DbSet<LENGUAJE> LENGUAJE { get; set; }
        public virtual DbSet<MODULO> MODULO { get; set; }
        public virtual DbSet<MOTOR_BASE_DATOS> MOTOR_BASE_DATOS { get; set; }
        public virtual DbSet<ORGANIZACION> ORGANIZACION { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<RACK> RACK { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<SALA_SERVIDORES> SALA_SERVIDORES { get; set; }
        public virtual DbSet<SEGURIDAD> SEGURIDAD { get; set; }
        public virtual DbSet<SENSIBILIDAD> SENSIBILIDAD { get; set; }
        public virtual DbSet<SERVICIOS> SERVICIOS { get; set; }
        public virtual DbSet<SERVIDOR> SERVIDOR { get; set; }
        public virtual DbSet<SISTEMA> SISTEMA { get; set; }
        public virtual DbSet<SISTEMA_OPERATIVO> SISTEMA_OPERATIVO { get; set; }
        public virtual DbSet<SOLUCION> SOLUCION { get; set; }
        public virtual DbSet<TICKET> TICKET { get; set; }
        public virtual DbSet<TIPO> TIPO { get; set; }
        public virtual DbSet<TIPO_NIVEL> TIPO_NIVEL { get; set; }
        public virtual DbSet<TIPO_SERVICIO> TIPO_SERVICIO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
