//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class HASH_PASS_BASE_DATOS
    {
        public string COD_MODULO { get; set; }
        public string HASH_PASS { get; set; }
    
        public virtual BASE_DATOS BASE_DATOS { get; set; }
    }
}
