//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODULO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MODULO()
        {
            this.TICKET = new HashSet<TICKET>();
            this.FUNCIONARIO = new HashSet<FUNCIONARIO>();
            this.PROVEEDOR = new HashSet<PROVEEDOR>();
        }
    
        public string COD_MODULO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<decimal> GARANTIA { get; set; }
        public decimal ID_DOCUMENTO { get; set; }
    
        public virtual BASE_DATOS BASE_DATOS { get; set; }
        public virtual DOCUMENTO DOCUMENTO { get; set; }
        public virtual SERVICIOS SERVICIOS { get; set; }
        public virtual SERVIDOR SERVIDOR { get; set; }
        public virtual SISTEMA SISTEMA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKET> TICKET { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FUNCIONARIO> FUNCIONARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROVEEDOR> PROVEEDOR { get; set; }
    }
}
