//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RACK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RACK()
        {
            this.SERVIDOR = new HashSet<SERVIDOR>();
        }
    
        public decimal ID_RACK { get; set; }
        public Nullable<decimal> UNIDAD_RACK { get; set; }
        public decimal ID_SALA_SERVIDOR { get; set; }
    
        public virtual SALA_SERVIDORES SALA_SERVIDORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVIDOR> SERVIDOR { get; set; }
    }
}
