//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVIDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVIDOR()
        {
            this.BASE_DATOS = new HashSet<BASE_DATOS>();
            this.SERVICIOS = new HashSet<SERVICIOS>();
            this.SISTEMA = new HashSet<SISTEMA>();
        }
    
        public string COD_SERVIDOR { get; set; }
        public string IP { get; set; }
        public Nullable<decimal> DISCO_DURO { get; set; }
        public Nullable<decimal> RAM { get; set; }
        public decimal ID_SO { get; set; }
        public decimal ID_RACK { get; set; }
        public decimal ID_TIPO_NIVEL { get; set; }
        public decimal ID_TIPO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BASE_DATOS> BASE_DATOS { get; set; }
        public virtual HASH_PASS_SERVIDOR HASH_PASS_SERVIDOR { get; set; }
        public virtual MODULO MODULO { get; set; }
        public virtual RACK RACK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIOS> SERVICIOS { get; set; }
        public virtual SISTEMA_OPERATIVO SISTEMA_OPERATIVO { get; set; }
        public virtual TIPO TIPO { get; set; }
        public virtual TIPO_NIVEL TIPO_NIVEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SISTEMA> SISTEMA { get; set; }
    }
}
