//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERVICIOS()
        {
            this.BASE_DATOS = new HashSet<BASE_DATOS>();
            this.SISTEMA = new HashSet<SISTEMA>();
        }
    
        public string COD_SERVICIO { get; set; }
        public string COD_SERVIDOR { get; set; }
        public decimal ID_TIPO { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal ID_LENGUAJE { get; set; }
    
        public virtual LENGUAJE LENGUAJE { get; set; }
        public virtual MODULO MODULO { get; set; }
        public virtual SERVIDOR SERVIDOR { get; set; }
        public virtual TIPO_SERVICIO TIPO_SERVICIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BASE_DATOS> BASE_DATOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SISTEMA> SISTEMA { get; set; }
    }
}
