//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SISTEMA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SISTEMA()
        {
            this.BASE_DATOS = new HashSet<BASE_DATOS>();
            this.ORGANIZACION = new HashSet<ORGANIZACION>();
            this.SERVICIOS = new HashSet<SERVICIOS>();
        }
    
        public string CODIGO_SISTEMA { get; set; }
        public decimal ID_SENSIBILIDAD { get; set; }
        public decimal ID_SEGURIDAD { get; set; }
        public string COD_SERVIDOR { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal ID_LENGUAJE { get; set; }
    
        public virtual LENGUAJE LENGUAJE { get; set; }
        public virtual MODULO MODULO { get; set; }
        public virtual SEGURIDAD SEGURIDAD { get; set; }
        public virtual SENSIBILIDAD SENSIBILIDAD { get; set; }
        public virtual SERVIDOR SERVIDOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BASE_DATOS> BASE_DATOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORGANIZACION> ORGANIZACION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVICIOS> SERVICIOS { get; set; }
    }
}
