//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TICKET()
        {
            this.SOLUCION = new HashSet<SOLUCION>();
        }
    
        public decimal ID_TICKET { get; set; }
        public System.DateTime FECHA_PROBLEMA { get; set; }
        public string PROBLEMA { get; set; }
        public string RUT_FUNCIONARIO { get; set; }
        public string MODULO_COD_MODULO { get; set; }
        public string NOMBRE_MODULO { get; set; }
    
        public virtual FUNCIONARIO FUNCIONARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOLUCION> SOLUCION { get; set; }
    }
}
